name: build
on:
  push:
  pull_request:

jobs:

  ci-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: setup-python
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
            3.13

      # get the week of the year (1-52) for cache control
      # this ensures that at least weekly we'll test with a clear cache
      - name: set .weeknum.txt
        run: /bin/date -u "+%U" > .weeknum.txt
        shell: bash

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true
          cache-dependency-glob: ".weeknum.txt"

      - run: uv tool install tox --with tox-uv

      - name: test
        run: tox run -m ci

  other-tox-checks:
    strategy:
      matrix:
        include:
          - pythons: ["3.9", "3.13"]
            tox_label: "ci-mypy"
          - pythons: ["3.13"]
            tox_label: "ci-package-check"

    runs-on: ubuntu-latest
    name: "Run '${{ matrix.tox_label }}'"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: setup-python
        with:
          python-version: "${{ join( matrix.pythons, '\n') }}"

      # get the week of the year (1-52) for cache control
      # this ensures that at least weekly we'll test with a clear cache
      - name: set .weeknum.txt
        run: /bin/date -u "+%U" > .weeknum.txt
        shell: bash

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true
          cache-dependency-glob: ".weeknum.txt"

      - run: uv tool install tox --with tox-uv

      - run: tox run -m "${{ matrix.tox_label }}"
